
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link:   "pgsql:postgres:123456@tcp(192.168.0.100:5432)/gvadmindb"
        path: "./internal/app/submission"
        tables:          "shop"
        tablesEx:        ""
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
    # service:
    #   srcFolder: "internal/app/system/logic"
    #   dstFolder:  "internal/app/system/service"